
server:
  port: 8081


eureka:
  instance:
    prefer-ip-address: true
spring:
  application:
    name: proxy-server
  cloud:
    gateway:
      routes:
        - id: plantModule
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/plants/**
        - id: sensorModule
          uri: http://localhost:8085/
          predicates:
            - Path=/api/v1/sensors/**
        - id: breakdownModule
          uri: http://localhost:8084/
          predicates:
            - Path=/api/v1/breakdowns/**
        - id: maintenanceModule
          uri: http://localhost:3000/
          predicates:
            - Path=/maintenace/**