
server:
  port: 8081


eureka:
  instance:
    prefer-ip-address: true
spring:
  application:
    name: proxy-server
  cloud:
    gateway:
      routes:
        - id: carLocationModule
          uri: http://localhost:8081/
          predicates:
            - Path=/car-location-service/**
        - id: userModule
          uri: http://localhost:8082/
          predicates:
            - Path=/userManager/**
        - id: vehiculeModule
          uri: http://localhost:8083/
          predicates:
            - Path=/api/vehicules/**
        - id: maintenanceModule
          uri: http://localhost:3000/
          predicates:
            - Path=/maintenace/**